name: TestWorkflow

on:
  push:
    branches:
      - main
    paths-ignore:
      - "**/*.md"
      - "*.sh"
      - "Dockerfile"

jobs:
  test:
    container:
      image: golang:1.25.4-alpine
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: go test ./... -cover -coverprofile ./coverage.out
      - run: go tool cover -func ./coverage.out | tail -1